version: '3'

name: 'dashboard'

networks:
  dashboard-network:
    driver: bridge

volumes:
  dashboard-postgres:
  dashboard-redis:

services:
  redis:
    image: redis:latest
    container_name: dashboard-redis
    restart: unless-stopped
    networks:
      - dashboard-network
    volumes:
      - dashboard-redis:/data
    expose:
      - '6379'
  postgres:
    image: postgres:latest
    container_name: dashboard-postgres
    restart: unless-stopped
    networks:
      - dashboard-network
    volumes:
      - dashboard-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - ${POSTGRES_PORT}
  server:
    image: node:alpine
    container_name: server
    restart: unless-stopped
    networks:
      - dashboard-network
    working_dir: /usr/dashboard
    command: yarn run dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/dashboard
      - ./src/db/migrations:/usr/dashboard/src/db/migrations:rw
    depends_on:
      - postgres
      # - redis
    env_file:
      - .env