version: '3'

name: 'dashbaord'

networks:
  dashbaord-network:
    driver: bridge

volumes:
  dashbaord-postgres:
  dashbaord-redis:

services:
  redis:
    image: redis:latest
    container_name: dashbaord-redis
    restart: unless-stopped
    networks:
      - dashbaord-network
    volumes:
      - dashbaord-redis:/data
    expose:
      - '6379'
  postgres:
    image: postgres:latest
    container_name: dashbaord-postgres
    restart: unless-stopped
    networks:
      - dashbaord-network
    volumes:
      - dashbaord-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - ${POSTGRES_PORT}
  server:
    image: node:alpine
    container_name: server
    restart: unless-stopped
    networks:
      - dashbaord-network
    working_dir: /usr/dashbaord
    command: yarn run dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/dashbaord
      - ./src/db/migrations:/usr/dashbaord/src/db/migrations:rw
    depends_on:
      - postgres
      # - redis
    env_file:
      - .env